# Generated by Django 3.0.4 on 2020-03-24 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('timezone', models.IntegerField()),
                ('weeks', models.IntegerField()),
                ('students', models.IntegerField()),
                ('current_students', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('timezone', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('has_mentor', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='match.Mentor')),
            ],
        ),
    ]
