# Generated by Django 3.0.4 on 2020-03-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('timezone', models.IntegerField()),
                ('daytime', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='match.Person')),
                ('details', models.TextField()),
                ('students', models.IntegerField()),
                ('weeks', models.IntegerField()),
            ],
            bases=('match.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='skill_set',
            field=models.ManyToManyField(to='match.Skill'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='match.Person')),
                ('lost_job', models.BooleanField(default=True)),
                ('current_mentor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='match.Mentor')),
            ],
            bases=('match.person',),
        ),
    ]
