# Generated by Django 3.0.4 on 2020-03-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='form_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentor',
            name='details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
