# Generated by Django 3.0.4 on 2020-03-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20200324_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
