# Generated by Django 3.0.4 on 2020-03-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20200326_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': 'Technologies'},
        ),
        migrations.AddField(
            model_name='person',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(blank=True, to='match.Skill'),
        ),
    ]
