# Generated by Django 3.0.4 on 2020-04-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_student_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'All Users'},
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='form_value',
        ),
    ]
