# Generated by Django 3.0.4 on 2020-05-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20200405_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='status',
            field=models.CharField(choices=[('retainer', 'retainer'), ('active', 'active'), ('paused', 'paused'), ('volunteer', 'volunteer'), ('unresponsive', 'unresponsive'), ('alum', 'alum')], default='volunteer', max_length=20),
        ),
        migrations.AddField(
            model_name='mentor',
            name='students_graduated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('lead', 'lead'), ('hot-lead', 'hot-lead'), ('beta', 'beta'), ('pro-bono', 'pro-bono'), ('student', 'student'), ('paused', 'paused'), ('drop-out', 'drop-out'), ('unresponsive', 'unresponsive'), ('retainer', 'retainer'), ('alum', 'alum')], default='student', max_length=20),
        ),
    ]
